2018-03-06 21:04:43 [scrapy.utils.log] INFO: Scrapy 1.3.3 started (bot: scrapybot)
2018-03-06 21:04:43 [scrapy.utils.log] INFO: Overridden settings: {'SPIDER_LOADER_WARN_ONLY': True, 'FEED_URI': 'Duma/Reports/Duma-2018-03-06.json'}
2018-03-06 21:04:44 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.corestats.CoreStats']
2018-03-06 21:04:45 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2018-03-06 21:04:45 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2018-03-06 21:04:45 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2018-03-06 21:04:45 [scrapy.core.engine] INFO: Spider opened
2018-03-06 21:04:45 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2018-03-06 21:04:45 [scrapy.extensions.telnet] DEBUG: Telnet console listening on 127.0.0.1:6023
2018-03-06 21:05:09 [scrapy.downloadermiddlewares.redirect] DEBUG: Redirecting (302) to <GET http://www.duma.bg/taxonomy/term/1> from <GET http://duma.bg/taxonomy/term/1>
2018-03-06 21:05:10 [scrapy.downloadermiddlewares.redirect] DEBUG: Redirecting (302) to <GET http://www.duma.bg/taxonomy/term/4/1> from <GET http://duma.bg/taxonomy/term/4/1>
2018-03-06 21:05:10 [scrapy.downloadermiddlewares.redirect] DEBUG: Redirecting (302) to <GET http://www.duma.bg/taxonomy/term/2> from <GET http://duma.bg/taxonomy/term/2>
2018-03-06 21:05:10 [scrapy.downloadermiddlewares.redirect] DEBUG: Redirecting (302) to <GET http://www.duma.bg/taxonomy/term/3/1> from <GET http://duma.bg/taxonomy/term/3/1>
2018-03-06 21:05:10 [scrapy.downloadermiddlewares.redirect] DEBUG: Redirecting (302) to <GET http://www.duma.bg/taxonomy/term/5/1> from <GET http://duma.bg/taxonomy/term/5/1>
2018-03-06 21:05:11 [scrapy.downloadermiddlewares.redirect] DEBUG: Redirecting (302) to <GET http://www.duma.bg/taxonomy/term/6/1> from <GET http://duma.bg/taxonomy/term/6/1>
2018-03-06 21:05:45 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2018-03-06 21:06:24 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://www.duma.bg/taxonomy/term/6/1> (referer: None)
2018-03-06 21:06:33 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://www.duma.bg/taxonomy/term/2> (referer: None)
2018-03-06 21:06:45 [scrapy.extensions.logstats] INFO: Crawled 2 pages (at 2 pages/min), scraped 0 items (at 0 items/min)
2018-03-06 21:07:26 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://www.duma.bg/taxonomy/term/5/1> (referer: None)
2018-03-06 21:07:43 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://www.duma.bg/taxonomy/term/3/1> (referer: None)
2018-03-06 21:07:45 [scrapy.extensions.logstats] INFO: Crawled 4 pages (at 2 pages/min), scraped 0 items (at 0 items/min)
2018-03-06 21:08:07 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://www.duma.bg/taxonomy/term/1> (referer: None)
2018-03-06 21:08:10 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET http://www.duma.bg/taxonomy/term/4/1> (failed 1 times): User timeout caused connection failure: Getting http://www.duma.bg/taxonomy/term/4/1 took longer than 180.0 seconds..
2018-03-06 21:08:45 [scrapy.extensions.logstats] INFO: Crawled 5 pages (at 1 pages/min), scraped 0 items (at 0 items/min)
2018-03-06 21:09:45 [scrapy.extensions.logstats] INFO: Crawled 5 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2018-03-06 21:10:45 [scrapy.extensions.logstats] INFO: Crawled 5 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2018-03-06 21:11:10 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET http://www.duma.bg/taxonomy/term/4/1> (failed 2 times): User timeout caused connection failure: Getting http://www.duma.bg/taxonomy/term/4/1 took longer than 180.0 seconds..
2018-03-06 21:11:45 [scrapy.extensions.logstats] INFO: Crawled 5 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2018-03-06 21:12:45 [scrapy.extensions.logstats] INFO: Crawled 5 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2018-03-06 21:13:45 [scrapy.extensions.logstats] INFO: Crawled 5 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2018-03-06 21:14:10 [scrapy.downloadermiddlewares.retry] DEBUG: Gave up retrying <GET http://www.duma.bg/taxonomy/term/4/1> (failed 3 times): User timeout caused connection failure: Getting http://www.duma.bg/taxonomy/term/4/1 took longer than 180.0 seconds..
2018-03-06 21:14:10 [scrapy.core.scraper] ERROR: Error downloading <GET http://www.duma.bg/taxonomy/term/4/1>
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\twisted\internet\defer.py", line 1299, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "c:\python27\lib\site-packages\twisted\python\failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "c:\python27\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "c:\python27\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "c:\python27\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 306, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
TimeoutError: User timeout caused connection failure: Getting http://www.duma.bg/taxonomy/term/4/1 took longer than 180.0 seconds..
2018-03-06 21:14:11 [scrapy.core.engine] INFO: Closing spider (finished)
2018-03-06 21:14:11 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/exception_count': 3,
 'downloader/exception_type_count/twisted.internet.error.TimeoutError': 3,
 'downloader/request_bytes': 3132,
 'downloader/request_count': 14,
 'downloader/request_method_count/GET': 14,
 'downloader/response_bytes': 50734,
 'downloader/response_count': 11,
 'downloader/response_status_count/200': 5,
 'downloader/response_status_count/302': 6,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2018, 3, 6, 19, 14, 11, 35000),
 'log_count/DEBUG': 15,
 'log_count/ERROR': 1,
 'log_count/INFO': 16,
 'response_received_count': 5,
 'scheduler/dequeued': 14,
 'scheduler/dequeued/memory': 14,
 'scheduler/enqueued': 14,
 'scheduler/enqueued/memory': 14,
 'start_time': datetime.datetime(2018, 3, 6, 19, 4, 45, 697000)}
2018-03-06 21:14:11 [scrapy.core.engine] INFO: Spider closed (finished)
